spring.application.name=Cloud-Api-Gateway
server.port=3333
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

spring.cloud.gateway.routes[0].id=welcome-api
spring.cloud.gateway.routes[0].uri=lb://WELCOME-API
spring.cloud.gateway.routes[0].predicates[0]=Path=/welcome

spring.cloud.gateway.routes[1].id=greet-api
spring.cloud.gateway.routes[1].uri=lb://GREET-API
spring.cloud.gateway.routes[1].predicates[0]=Path=/greet